# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'collectively' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for collectively
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'

  target 'collectivelyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'collectivelyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
