# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'collectively' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for collectively
    pod 'p2.OAuth2'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Alamofire'
    pod 'Localize-Swift'
    pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :branch => 'release/swift4'
    pod 'Kingfisher'
    
  target 'collectivelyTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Quick'
   	pod 'Nimble'
  end

  target 'collectivelyUITests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Quick'
    	pod 'Nimble'
  end

end
